### ISSUE TITLE
Example with keys or values of a complex ocaml type

### ISSUE THREAD

**Issue by struktured** [orbitz/ocaml-riakc#12]
The examples in the src/examples directory seem to demonstrate the operations adequately but only for primitive string types. 

Can an example be provided when the key or value type is something less trivial than a string, such as a variant type or record?

**Comment by orbitz** [comment]
Riak 1.x only stores binary blobs.  Serializing those binary blobs to and from ocaml data types is something that should happen at a higher level than this library.

**Comment by struktured** [comment]
Ok, would you suggest something like Jane Street's bin_prot then?

**Comment by orbitz** [comment]
Highly dependent on your use-case, of course.  I would suggest using whatever serializer/deserializer library you feel comfortable with.  Given that it's a database I would generally suggest using a format which has implementations in multiple languages.

**Comment by struktured** [comment]
Ok, thanks for your fast responses to my questions.
