### ISSUE TITLE
Setting 2i on a new object

### ISSUE THREAD

**Issue by xandkar** [orbitz/ocaml-riakc#4]
`Riakc.Robj.Pair.t` is abstract and has no setters exposed. Is that intentional?
How would one set a 2i when creating a new object?

**Comment by orbitz** [comment]
Right now riakc doesn't have 2i support.  Patches welcome!  If not I might try to add it in this weekend.  It shouldn't be hard, not much more than filling in the current stub.

**Comment by orbitz** [comment]
Here are modifications to add 2i to put/get, no search yet though, be so kind and do a quick review:

https://github.com/orbitz/ocaml-riakc/compare/master...feature-2i-put-support

**Comment by orbitz** [comment]
Merged in to master!  Will be in next release.
